### PR TITLE
add SDL2_mixer sample

### PR DESCRIPTION
**Pull request by diamant3**
This is my PR for sdl2_mixer sample. The audio will play after starting the program and it can pause or resume using the cross or circle buttons, respectively. thanks!

result: [website](https://diamant3.github.io/pspdev.github.io/)

### CODE REVIEW

**Comment by diamant3** [comment]
Can someone review my PR and let me know if it is acceptable or not? Thanks!

**Review by sharkwouter — CHANGES_REQUESTED** [review]
Sorry I didn't get to it earlier. This is looking good, but I would like to request one change. Could you create a directory called resources, add the audio file to it and link to it in the audio examples? That would make it more accessible.

**Comment by diamant3** [comment]
It's alright. Thanks for taking the time to review my PR! Yes, I will do that right away.

**Comment by diamant3** [comment]
I used `https://github.com/pspdev/pspdev.github.io/resources` to link the audio file. What do you think?

PS: the audio file is safe; I keep my windows up to date and have an antivirus program. 😅

**Pull request merged**
