### PR TITLE
Add information on debugging

### PR DESCRIPTION
**Pull request by sharkwouter**
This is mostly a copy of information on the psplink website (which I wrote, so there are no licensing issues). This adds the basics on how to debug the code people write for the PSP. I think this was the one part that was still missing from the website.

### CODE REVIEW

**Comment by tpimh** [comment]
A very welcome addition indeed.

I wonder if anyone is using some automated VSCode setup for debugging with gdb?

I only used USB for debugging, but I heard that there's also a serial debugger (should be useful for debugging USB). Maybe gdb server can be added to PPSSPP?

**Comment by sharkwouter** [comment]
Thanks!

> I wonder if anyone is using some automated VSCode setup for debugging with gdb?

We've had a lot of people ask for this and it is possible, but I don't know anyone who has it set up. If you have that configured, it would be great if you could add how to set it up.

> Maybe gdb server can be added to PPSSPP?

I would say this would not be useful, since PPSSPP does not emulate the hardware well enough for the result to be useful.

**Comment by tpimh** [comment]
Some things do no need to be accurate to be useful, I believe the reverse engineering of commercial PSP games is done with PPSSPP (using some WebSocket API, not gdb), so it can also be useful for homebrew.

**Comment by sharkwouter** [comment]
That's fair, it would help some people. These things always remind me of a gamejam we did where most of the people developed their game on PPSSPP and only 3 of the games out of 8 actually worked on real hardware. The one that won was the only one that ran at a decent speed on the PSP.

**Comment by diamant3** [comment]
Thanks for working on this! looks good to me, I'll merge this now.

**Pull request merged**
