### PR TITLE
Make pspdev.github.io useful

### PR DESCRIPTION
**Pull request by sharkwouter**
More information can be added later, but with these changes there are at least instructions on how to install and use the toolchain on Ubuntu. Mac and msys2 should be added, but I can't do that right now. Feel free to squish this, as it is a lot of commit.

The result of the changes can be viewed here: https://sharkwouter.github.io/pspdev.github.io/

### CODE REVIEW

**Comment by sharkwouter** [comment]
Feel free to squish this. The result of the changes can be viewed here: https://sharkwouter.github.io/pspdev.github.io/

**Comment by fjtrujy** [comment]
Super! That's is a really nice idea!

**Comment by sharkwouter** [comment]
@fjtrujy I cannot merge in this repository unfortunately. If you could do that, that would be appreciated.

**Comment by sharkwouter** [comment]
Thanks for merging! I'll get on some changes which should be reviewed individually.

**Pull request merged**
