### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by diamant3**
move the "installing dependencies" to "installing" heading for readability

- use markdown as possible
- fix indentation in code of samples

### CODE REVIEW

**Review by sharkwouter — CHANGES_REQUESTED** [review]
Thanks for the merge request! It mostly seems like an improvement. Unfortunately using markdown within a details tag does not work in GitHub Pages, so I'm not able to merge this without causing breakage.

**Comment by diamant3** [comment]
thank you so much for reviewing my pr!, this is the result of [website](https://diamant3.github.io/pspdev.github.io/) in my update-readme branch

**Comment by diamant3** [comment]
Sorry for the messy commits. I will close this and do another PR.

**Comment by sharkwouter** [comment]
Okay, I'm looking forward to the next PR then

**Pull request closed without merging**
